### ISSUE TITLE
Pull in information from github api

### ISSUE THREAD

**Issue by mrozbarry** [bdo/gitpair#13]
I could see something really simple like `./node_modules/.bin/git-pair --add mrozbarry` and it would query the github api and add that user to my config.

**Comment by mrozbarry** [comment]
Maybe related to #8

**Comment by bdo** [comment]
Very good suggestion, and agreed that it would fit nicely into the API

**Comment by bdo** [comment]
From @mrozbarry's comment in #16:
 
Should there be support for other services? Thinking maybe bitbucket and gitlab (which may require additional config), and possibly others?

**Comment by bdo** [comment]
Hi @mrozbarry, while implementing #19, I had a look at implementing this feature.
Unfortunately, I found that a lot of devs I was pairing with do not expose the email address publicly, which means it's `null`... 😢
