### ISSUE TITLE
Add per-project pairing settings

### ISSUE THREAD

**Issue by mrozbarry** [bdo/gitpair#15]
I work with a larger team, and it doesn't make a lot of sense for me to add them all as potential contributors to every project.

**Comment by bdo** [comment]
+1 for this

**Comment by mrozbarry** [comment]
Just as a heads up, I've forked, and am working on a big change that tackles all my issues (#13, #14, and #15), implements #4, and probably lays some groundwork for #8 and #6 . I'll have more details in the PR, which I should have some time to clean up and finish this weekend.

**Comment by bdo** [comment]
Fixed by #19.
