### ISSUE TITLE
Add option to amend command to specify a number of commit to rewrite in history

### ISSUE THREAD

**Issue by GDuparquet** [bdo/gitpair#21]
Sometimes, we forget to `gitpair amend` during a development. It could be useful to have an option allowing us to write something like 
```
gitpair amend -n 3
```
that would rewrite the `-n` last commits in log history.

**Comment by mrozbarry** [comment]
You could probably achieve this currently with a rebase, but I'd have to experiment.

From my perspective, and @bdo could chime in more on his vision, it seems like an out-of-scope solution; If I were using git, and wanted to change the authors, I'd rebase the commits I want to change.

**Comment by GDuparquet** [comment]
@mrozbarry I agree. But this is only working if you use the post-commit setup. If your team wants your repository to keep clear of gitpair config, you won't be able to proceed such an operation.

**Comment by mrozbarry** [comment]
I can't foresee any reason why you could do something like:

```
npm install -g gitpair
```

And

`.git/hooks/pre-commit`:
```
gitpair amend
```

You shouldn't be committing the `.git` directory, so it stays out of your shared repository, and installing gitpair globally keeps it out of your package.json, too.
```

**Comment by GDuparquet** [comment]
@mrozbarry you're right. I was thinking about the husky example without considering using the git own setup.

`-n` option could be useful if you don't want to set git hooks up, though.

**Comment by bdo** [comment]
@GDuparquet Thanks for the suggestion. It is something you probably may want to do from time to time, e.g. when you forgot to run `git pair with` a do a series of commits. However as @mrozbarry explains, with the typical setup of gitpair where you have it installed with git hooks, it's not going to happen very often.

Intuitively, I can't think of a *easy* way to implement this. If you have a suggestion on how we could implement this in a relatively simple way, I'd be happy to look into it.

**Comment by bdo** [comment]
Closing this for now, but happy to take suggestions if this can be done easily.

**Comment by bdo** [comment]
For those wanting to exec gitpair on all your commits (up to \<COMMIT-SHA1\>), you can use
```
git rebase --exec 'npx gitpair amend' <COMMIT-SHA1>^
```
